#!/bin/bash
# Trigger First Avenue company creation via Temporal CLI or API

echo "🏢 Creating First Avenue Company"
echo "================================"
echo ""
echo "✅ Configuration verified:"
echo "   - Worker: RUNNING"
echo "   - Cloudinary: CONFIGURED"
echo "   - Flux API: CONFIGURED  "
echo "   - Style: Semi-cartoon illustration"
echo ""
echo "📋 Company Details:"
echo "   URL: https://www.firstavenue.com/"
echo "   Category: Placement Agent"
echo "   Expected Images: 2 (Featured + Hero)"
echo "   Style: Semi-cartoon, NOT photorealistic"
echo "   Colors: Navy blue, charcoal gray, tech blue"
echo ""
echo "⏰ Timeline:"
echo "   0-60s:   Research & scraping"
echo "   60-90s:  Profile generation"
echo "   90-180s: 🎨 Image generation (Kontext Max)"
echo "   180s+:   Database save & Zep sync"
echo ""
echo "======================================"
echo "TO START THE WORKFLOW:"
echo "======================================"
echo ""
echo "Go to: https://cloud.temporal.io/"
echo "Namespace: quickstart-quest.zivkb"
echo "Click: 'Start Workflow'"
echo ""
echo "Use this input:"
echo '{'
echo '  "url": "https://www.firstavenue.com/",'
echo '  "category": "placement",'
echo '  "app": "placement",'
echo '  "jurisdiction": "US",'
echo '  "force_update": false'
echo '}'
echo ""
echo "Task Queue: quest-company-queue"
echo "Workflow Type: CompanyCreationWorkflow"
echo ""
echo "======================================"
echo "MONITORING:"
echo "======================================"
echo ""
echo "Watch Phase 7 logs for:"
echo "  → 'Generating contextual brand images (Flux Kontext Max)'"
echo "  → 'Generating company featured image with kontext-max'"
echo "  → 'Generating company hero image with kontext-max'"
echo "  → 'Uploaded to Cloudinary: https://res.cloudinary.com/...'"
echo ""
echo "When complete, you'll see:"
echo "  → featured_image_url"
echo "  → hero_image_url"
echo ""
echo "Open those URLs to see the semi-cartoon magic! 🎨"
echo ""
