name: Semgrep Security Scan

on:
  pull_request: {}
  push:
    branches: ["main"]
  schedule:
    # Run once a week on Sunday
    - cron: '0 0 * * 0'

jobs:
  semgrep:
    name: Security Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Semgrep
        run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: semgrep.sarif